In [1]:
import kagglehub
import pandas as pd

In [2]:
data = kagglehub.dataset_load(
    kagglehub.KaggleDatasetAdapter.PANDAS,
    "viveksingh2400/multitask-nlp",
    "open_multitask_nlp_v1_train.csv"
    )

In [13]:
data.head()

,text,sentiment,behavior_score,category_1,urgency
0,I am unable to access my account due to an iss...,negative,below_average,account_issue,high
1,I am extremely unhappy with the service I have...,negative,very_poor,complaint,critical
2,I am providing feedback to help improve the ov...,neutral,slightly_positive,feedback,low
3,I am reaching out because I need assistance un...,neutral,neutral,need_help,medium
4,I am extremely unhappy with the service I have...,negative,poor,complaint,critical

In [14]:
data.columns

Index(['text', 'sentiment', 'behavior_score', 'category_1', 'urgency'], dtype='object')

In [24]:
for i in ['sentiment', 'behavior_score', 'category_1', 'urgency']:
    print(f"{i}: ",data[i].unique())
    print("+-"*20)

sentiment:  ['negative' 'neutral' 'positive']
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-
behavior_score:  ['below_average' 'very_poor' 'slightly_positive' 'neutral' 'poor'
 'very_good' 'good' 'excellent']
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-
category_1:  ['account_issue' 'complaint' 'feedback' 'need_help' 'technical_issue'
 'feature_request' 'billing_payment' 'policy_question' 'service_delay'
 'general_inquiry' 'praise_appreciation' 'customer_opinion']
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-
urgency:  ['high' 'critical' 'low' 'medium']
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-

In [16]:
data.duplicated().sum()

np.int64(0)

In [22]:
data['urgency'].nunique()

4

In [17]:
data.to_csv('open_multitask_nlp_v1_train.csv',index=False)

In [10]:
pd.crosstab(data['sentiment'],data['urgency'])

urgency    critical  high   low  medium
sentiment
negative       2528  4214     0       0
neutral           0   828  4100    6660
positive          0     0  1850       0

In [12]:
data['category_1'].value_counts()

category_1
praise_appreciation    1850
policy_question        1744
account_issue          1731
general_inquiry        1728
technical_issue        1681
billing_payment        1676
complaint              1668
service_delay          1662
feedback               1648
feature_request        1624
customer_opinion       1586
need_help              1582
Name: count, dtype: int64

In [13]:
"""Repeated delays have caused inconvenience. This has affected my workflow. Thank you for taking the time to read this message. Thank you for taking the time to read this message. I believe this matter can be resolved. This has affected my
workflow. Thank you for taking the time to read this message."""

'Repeated delays have caused inconvenience. This has affected my workflow. Thank you for taking the time to read this message. Thank you for taking the time to read this message. I believe this matter can be resolved. This has affected my\nworkflow. Thank you for taking the time to read this message.'